config/routes.rb
Rails.application.routes.draw do

  resources :stories do
      member do
          post :like
      end
  end

  delete '/logout', to: 'sessions#destroy', as: :logout
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  root to: 'stories#index'
end

app/models/story.rb
class Story < ActiveRecord::Base

    belongs_to :user

    validates :title, presence: true
    validates :body, presence: true

    include PublicActivity::Model
    tracked owner: Proc.new { |controller, model| controller.current_user ? controller.current_user : nil }

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :stories

    class << self
        def from_omniauth(auth)
            user = User.find_or_initialize_by(uid: auth['uid'])
            user.name = auth['info']['name']
            user.oauth_token = auth.credentials.token
            user.oauth_expires_at = Time.at(auth.credentials.expires_at)
            user.avatar_url = auth['info']['image']
            user.save!
            user
        end
        private

        def current_user
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include PublicActivity::StoreController

  def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  hide_action :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.from_omniauth(request.env['omniauth.auth'])
        session[:user_id] = user.id
        flash[:success] = "Welcome, #{user.name}!"
        redirect_to root_url
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "Goodbye!"
        redirect_to root_url
    end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    before_action :find_story, only: [:destroy, :show, :edit, :update, :like]
    before_action :load_activities, only: [:index, :show, :new, :edit]

    def index
        @stories = Story.order('created_at DESC')
    end

    def like
        without_tracking do
            @story.increment!(:likes)
        end
        @story.create_activity :like
        flash[:success] = 'You liked this!'
        redirect_to story_path(@story)
    end

    def new
        @story = Story.new
    end

    def create
        @story = Story.new(story_params)
        if @story.save
            flash[:success] = 'Story added!'
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @story.update_attributes(story_params)
            flash[:success] = 'Story edited!'
            redirect_to root_path
        else
            render 'edit'
        end
    end

    def destroy
        if @story.destroy
            flash[:success] = 'Story deleted!'
        else
            flash[:error] = 'Cannot delete story...'
        end
        redirect_to root_path
    end

    def show
    end
    private
    def story_params
        params.require(:story).permit(:title,:body)
    end

    def find_story
        @story = Story.find(params[:id])
    end


    def load_activities
        @activities = PublicActivity::Activity.order('created_at DESC').limit(20)
    end

    def without_tracking
        Story.public_activity_off
        yield if block_given?
        Story.public_activity_on
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_header(header)
        content_for(:page_header) {header.to_s}
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsfeeder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<script>
jQuery ->
  $('body').prepend('<ul class="nav navbar-nav pull-right">')

  $.ajax
    url: "#{window.location.protocol}//connect.facebook.net/en_US/all.js"
    dataType: 'script'
    cache: true


window.fbAsyncInit = ->
  FB.init(appId: <%= ENV['FACEBOOK_APP_ID'] %>, cookie: true)

  $('#sign_in').click (e) ->
    e.preventDefault()
    FB.login (response) ->
      window.location = '/auth/facebook/callback' if response.authResponse

  $('#sign_out').click (e) ->
    FB.getLoginStatus (response) ->
      FB.logout() if response.authResponse
    true
</script>

<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <%= link_to 'Newsfeeder', root_path, class: 'navbar-brand' %>
            </div>
            <ul class="nav navbar-nav pull-right">
                <% if current_user %>
                    <li><span><%=image_tag current_user.avatar_url, alt: current_user.name %></span></li>
                    <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
                <%else%>
                    <li><%= link_to 'Log In', '/auth/facebook', id: "sign_in" %></li>
                <%end%>
            </ul>
        </div>
    </div>

    <div class="container">
        <div class="page-header">
            <h1><%=yield :page_header %></h1>
        </div>
        <% flash.each do |key,value| %>
        <div class="alert alert-<%=key%>">
            <%=value%>
        </div>
    </div>
    <%end%>
    <div class="col-sm-9">
        <%= yield %>
    </div>
    <%=render 'shared/activities' %>
</body>
</html>

app/views/public_activity/story/_create.html.erb
<li class="list-group-item">
    <span class="glyphicon glyphicon-plus"</span>
    <small class="text-muted"><%= a.created_at.strftime('%H:%M:%S %-d %B %Y')%></small><br/>
    <strong><%=activity.owner ? activity.owner.name : 'Guest' %></strong>
    <% if a.trackable %>
        <%= link_to a.trackable.title, story_path(a.trackable) %> was created.
    <%else%>
        An article that was deleted was added.
    <%end%>
</li>

app/views/public_activity/story/_destroyed.html.erb
<li class="list-group-item">
    <span class="glyphicon glyphicon-plus"</span>
    <small class="text-muted"><%= a.created_at.strftime('%H:%M:%S %-d %B %Y')%></small><br/>
    <strong><%=activity.owner ? activity.owner.name : 'Guest' %></strong>
    An article was deleted.
</li>

app/views/public_activity/story/_update.html.erb
<li class="list-group-item">
    <span class="glyphicon glyphicon-plus"</span>
    <small class="text-muted"><%= a.created_at.strftime('%H:%M:%S %-d %B %Y')%></small><br/>
    <strong><%=activity.owner ? activity.owner.name : 'Guest' %></strong>
    <% if a.trackable %>
        <%= a.trackable.title %> was edited.
    <%else%>
        An article that was delted was edited.
    <%end%>
</li>

app/views/shared/_activities.html.erb
<div class="col-sm-3">
    <ul class="list-group">
        <% @activities.each do |activity| %>
        <li class="list-group-item">
            <span class="glyphicon glyphicon-<%=activity.key.match(/\.(.*)/)[1]%>"></span>
            <strong><%=activity.owner ? activity.owner.name : 'Guest' %></strong>
            <%= render_activity activity, display: :i18n %>
            <% if activity.trackable %>
                "<%= link_to activity.trackable.title, story_path(activity.trackable) %>"
            <% else %>
                with unknown title.
            <% end %>
        </li>
        <%end%>
    </ul>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title">The following errors were found while submitting your post:</h3>
        </div>

        <div class="panel-body">
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                <li><%=msg%></li>
                <%end%>
            </ul>
        </div>
    </div>
<%end%>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
    <%= render 'shared/errors', object: @story %>

    <div class="form-group">
        <%=f.label :title%>
        <%=f.text_field :title, class: 'form-control', required: true%>
    </div>

    <div class="form-group">
        <%=f.label :body%>
        <%=f.text_area :body, class: 'form-control', required: true, cols: 3 %>
    </div>

    <%= f.submit 'Post', class: 'btn btn-primary' %>
<%end%>

app/views/stories/edit.html.erb
<%page_header "Edit Story" %>
<%=render 'form'%>

app/views/stories/index.html.erb
<%page_header "Top Stories" %>
<p><%=link_to 'Add One!', new_story_path, class: 'btn btn-primary btn-large'%></p>
<% @stories.each do |story| %>
    <div class="well well-lg">
        <h2><%=link_to story.title, story_path(story) %></h2>

        <p><%=truncate(story.body, length: 350) %></p>

        <div class="btn-group">
            <%= link_to 'Edit', edit_story_path(story), class: 'btn btn-info' %>
            <%= link_to 'Delete', story_path(story), data: {confirm: 'Are you sure you want to delete this?'}, method: :delete, class: 'btn btn-danger'%>
        </div>
    </div>
<%end%>

app/views/stories/new.html.erb
<%page_header "New Story" %>
<%=render 'form' %>

app/views/stories/show.html.erb
<%page_header @story.title %>
<p>
  <span class="label label-default"><%= pluralize(@story.likes, 'like') %></span>
  <%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-thumbs-up') + ' Like it', like_story_path(@story), class: 'btn btn-default btn-sm', method: :post %>
</p>
<p><%=@story.title%></p>
<div class="btn-group">
    <%= link_to 'Edit', edit_story_path(@story), class: 'btn btn-info'%>
    <%= link_to 'Delete', story_path(@story), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-danger' %>
</div>
</div>